export const ASSETS = [
  { id: 'crypto-btc', name: 'Bitcoin', ticker: 'BTC', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/btc.svg', coingeckoId: 'bitcoin', placeholderPrice: 65000 },
  { id: 'crypto-eth', name: 'Ethereum', ticker: 'ETH', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/eth.svg', coingeckoId: 'ethereum', placeholderPrice: 3500 },
  { id: 'crypto-sol', name: 'Solana', ticker: 'SOL', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/sol.svg', coingeckoId: 'solana', placeholderPrice: 150 },
  { id: 'crypto-usdt', name: 'Tether', ticker: 'USDT', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/usdt.svg', coingeckoId: 'tether', placeholderPrice: 1 },
  { id: 'crypto-bnb', name: 'BNB', ticker: 'BNB', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/bnb.svg', coingeckoId: 'binancecoin', placeholderPrice: 600 },
  { id: 'crypto-xrp', name: 'XRP', ticker: 'XRP', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/xrp.svg', coingeckoId: 'ripple', placeholderPrice: 0.6 },
  { id: 'crypto-usdc', name: 'USD Coin', ticker: 'USDC', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/usdc.svg', coingeckoId: 'usd-coin', placeholderPrice: 1 },
  { id: 'crypto-ada', name: 'Cardano', ticker: 'ADA', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/ada.svg', coingeckoId: 'cardano', placeholderPrice: 0.5 },
  { id: 'crypto-avax', name: 'Avalanche', ticker: 'AVAX', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/avax.svg', coingeckoId: 'avalanche-2', placeholderPrice: 35 },
  { id: 'crypto-link', name: 'Chainlink', ticker: 'LINK', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/link.svg', coingeckoId: 'chainlink', placeholderPrice: 15 },
  { id: 'crypto-uni', name: 'Uniswap', ticker: 'UNI', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/uni.svg', coingeckoId: 'uniswap', placeholderPrice: 10 },
  { id: 'crypto-doge', name: 'Dogecoin', ticker: 'DOGE', type: 'crypto', minDeposit: 50, maxDeposit: 50000, logoUrl: '/assets/logos/crypto/doge.svg', coingeckoId: 'dogecoin', placeholderPrice: 0.15 },
  { id: 'stock-msft', name: 'Microsoft Corp.', ticker: 'MSFT', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/msft.svg', placeholderPrice: 420 },
  { id: 'stock-aapl', name: 'Apple Inc.', ticker: 'AAPL', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/aapl.svg', placeholderPrice: 190 },
  { id: 'stock-nvda', name: 'NVIDIA Corp.', ticker: 'NVDA', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/nvda.svg', placeholderPrice: 900 },
  { id: 'stock-googl', name: 'Alphabet Inc.', ticker: 'GOOGL', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/googl.svg', placeholderPrice: 175 },
  { id: 'stock-amzn', name: 'Amazon.com Inc.', ticker: 'AMZN', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/amzn.svg', placeholderPrice: 185 },
  { id: 'stock-meta', name: 'Meta Platforms Inc.', ticker: 'META', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/meta.svg', placeholderPrice: 500 },
  { id: 'stock-tsla', name: 'Tesla Inc.', ticker: 'TSLA', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/tsla.svg', placeholderPrice: 180 },
  { id: 'stock-brk-b', name: 'Berkshire Hathaway Inc.', ticker: 'BRK.B', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/brk-b.svg', placeholderPrice: 410 },
  { id: 'stock-lly', name: 'Eli Lilly and Co.', ticker: 'LLY', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/lly.svg', placeholderPrice: 800 },
  { id: 'stock-jpm', name: 'JPMorgan Chase & Co.', ticker: 'JPM', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/jpm.svg', placeholderPrice: 200 },
  { id: 'stock-v', name: 'Visa Inc.', ticker: 'V', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/v.svg', placeholderPrice: 275 },
  { id: 'stock-xom', name: 'Exxon Mobil Corp.', ticker: 'XOM', type: 'stock', minDeposit: 100, maxDeposit: 100000, logoUrl: '/assets/logos/stocks/xom.svg', placeholderPrice: 115 },
];
